### ISSUE TITLE
A doubt!

### ISSUE THREAD

**Issue by KiisterPlaster** [InTruder-Sec/IHA#1]
A doubt reading your article on RD.ME, I came across a quote from you in which it says... "It is impossible to reverse the MD5 Hash, in the same way it is **ALMOST** impossible to reverse the IHA hash, because it works on the principle of the keys and single modules". In this case, did you mean that there is still no definitive security in the IHA?

**Comment by InTruder-Sec** [comment]
Hey @KiisterPlaster 

It is impossible for a human to reverse this hashing algorithm manually. 

But as **NO SYSTEM IS SAFE** there may be a vulnerability  when someone try to reverse the code using some unique ways where the code fails.
